language: r

sudo: required

apt_packages:
  - texlive

script:
  - if [ "$TEST_SUITE" == "CRAN" ];then bash build.sh;else Rscript -e "source('tests/testthat.R', chdir = TRUE)";fi

after_success:
  - Rscript -e "library(covr);coveralls()"

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change

env:
  - R_REMOTES_NO_ERRORS_FROM_WARNINGS=TRUE
  global:
    - secure: "h06r9Nn7Y01TKEsPy9IWlSj38GopqKcjaNY5pH2/tRfQzNtlmDJKz2R028d5LtVk3tdpen6GTTKwDeWVmQUH63p6BffNjrhmB+JTk+2g4SSx8C8gJqSF0zPEIzz+8012PxXaW/4MIA8l/EJN1Y8ESxsLJNacBJYkWYNYLMCoRZ4="
  matrix:
    - TEST_SUITE=renderer1
    - TEST_SUITE=renderer2
    - TEST_SUITE=renderer3
    - TEST_SUITE=renderer4
    - TEST_SUITE=renderer5
    - TEST_SUITE=compiler
    - TEST_SUITE=CRAN
    
    
