language: r

sudo: required

apt_packages:
  - texlive

script:
  - R CMD INSTALL .
  - if [ "$TEST_SUITE" == "CRAN" ];then bash build.sh;else Rscript -e "source('tests/testthat.R', chdir = TRUE)";fi

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change

env:
  global:
    - R_REMOTES_NO_ERRORS_FROM_WARNINGS=TRUE 
  matrix:
    - TEST_SUITE=renderer1
    - TEST_SUITE=renderer2
    - TEST_SUITE=renderer3
    - TEST_SUITE=renderer4
    - TEST_SUITE=renderer5
    - TEST_SUITE=compiler
    - TEST_SUITE=CRAN
    
    
